export const status = {
    WAITING_RESPONSE_BUSINESS: 1,
    WAITING_TAKING_BY_DELIVER: 2,
    ORDER_ROUTING: 3,
    ORDER_CLOSED_WITH_SUCCESS: 4,
    ORDER_REFUSED: 0,
};
export const order = {
  SERVICE_CHARGE: 80
};
